name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Add Build Tools
      run: yarn global add build-tools
    - name: Download Steamworks SDK
      run: git clone https://github.com/TrueCarry/stmwrkssdk ../sdk
    - name: Yarn Install
      run: |
        echo $STEAMWORKS_SDK_PATH
        yarn install
      env:
        STEAMWORKS_SDK_PATH: /home/runner/work/sapic-ne/sdk/sdk
    - name: Build
      run: echo "hi"
